development:
  adapter: mysql2
  encoding: utf8
  database: spree
  pool: 5
  username: root
  password: carmatec
  reconnect: true
production:
  adapter: mysql2
  encoding: utf8
  database: spree
  pool: 5
  username: root
  password: carmatec
  reconnect: true